relatives = ["papa", "papaji", "papa ji", "baap", "dad", "sasurji", "sasur ji", "dady", "daddu", "father", "daddy",
             "papa jio", "abba", "appa", "baba", "abbu", "lala",
             "anna", "pappa", "pitaji", "pita ji", "pop", "pops", "bapuji", "bapu ji", "walid", "pa", "bapu", "vader",
             "babba",
             "yebba", "abbi", "pai", "awki", "aita", "pader", "peder", "otac", "buba", "tad", "patre", "patri",
             "papallu", "patra", "batu",
             "bato", "batico", "dada", "pare", "pattri", "opa", "daa", "da", "tata", "otec", "ate", "pappie", "pere",
             "poppa", "patro", "isa",
             "tatay", "itay", "tay", "ama", "heit", "banketi", "papi", "pater", "ru", "apa", "apu", "pabbi", "bapa",
             "ayah", "pak", "athair",
             "daidi", "babbo", "otosan", "padre", "babu", "bap", "bav", "pere", "pater", "atta", "tevs", "paire",
             "vajer", "pap", "tata", "tevas",
             "viejo", "paapa", "ray", "upa", "chaw", "chao", "babbas", "fader", "pee", "pate", "ta", "pate", "buwa",
             "faeder", "baabaa", "pitar",
             "tatah", "koro", "bab", "tama", "janak", "babbu", "fadar", "mzazi", "vatter", "dade", "kaka", "abbuji",
             "abbu ji", "abbujaan", "abbu jaan", "popa",
             "tad", "foter", "mummy", "mumma", "mamma", "mummyji", "mummy ji", "mammy", "mom", "mommy", "mammi", "ammi",
             "ammi ji", "ammiji", "ayi", "aayi", "aai",
             "amma", "ma", "maa", "matashri", "mata shri", "sasuma", "walida", "maji", "ma ji", "ba", "mata", "maai",
             'ai', "home", "mummy1", "mummy 1",
             "mummy2", "mummy 2", "motherinlaw", "mother in law", "mil", "moeder", "nene", "meme", "ahm", "matka",
             "majka", "mae", "mare", "mati", "maminka",
             "mor", "moer", "ema", "ina", "aiti", "maman", "mere", "mutter", "mana", "mitera", "manman", "makuahine",
             "anya", "fu", "induk", "ibu", "biang",
             "nyokap", "mathair", "madre", "okaasan", "mater", "motina", "madr", "maman", "mama", "mae", "mai",
             "mataji", "pabbo", "maica", "morsa", "anne", "ana",
             "valide", "mati", "ammee", "muter", "ama", "pabo", "amba", "avva", "abbe", "maasa", "mau", "bou",
             "peri appa", "periappa", "chinappa", "di", "didi", "sister",
             "jyeshttathi", "jyesthati", "Chechi", "oppol", "opa", "edathi", "edthi", "pengal", "iththa", "akkan",
             "akkachi", "sahodari", "anujati", "anujathi", "aniyathi", "thangai", "chelli",
             "choti", "thangi", "periamma", "peri amma", "mumaideu", "mota mama", "mamo", "mama", "mama ji", "mamaji",
             "mota mami", "nanda", "athai", "attayya", "mumani", "maaman", "ammavan", "mami",
             "mami ji", "mamiji" "jija", "jijaji", "jija ji" "jiju", "brother in law", "bil", "akka", "jethi", "jethai",
             "aapa", "maausi", "doddamma", "doddappa", "chikkamma", "chikkappa", "mavshi"
                                                                                 "saale sahab", "saali sahiba", "masi",
             "maasi", "masiji", "masi ji", "maasi ji", "maasiji", "mausi ji", "mausiji", "badepapa", "bade papaji",
             "bade papa ji", "badi mummy", "vahini", "mota pappa",
             "periyappa", "periyamma", "chitthi", "khuri", "kaki", "chaachi", "chaacha", "peusi", "devar ji", "devarji",
             "jeth ji", "jethji", "damadji", "damad ji",
             "badimummy", "badi mummyji", "badi mummy ji", "mausi", "bade papa", "badi mammi", "badi mammiji",
             "badi mammi ji", "choti maa", "chotima", "chotimaa", "choti mummy", "chote papa", "chacha",
             "chachi", "bua", "chachaji", "chacha ji", "chachi ji", "chachiji", "chachu", "mamu", "maamu", "taya",
             "taya ji", "tayaji", "tau", "tauji", "tau ji", "tayi",
             "tayiji", "tayi ji", "taayi", "taayiji", "taayi ji", "mausa", "mausa ji", "mausaji", "masad", "masad ji",
             "masadji", "bua ji", "buaji", "fufad", "fuffad",
             "fufad ji", "fufadji", "fufa", "fufaji", "fufa ji", "dada", "dadaji", "dada ji", "dadi", "dadiji",
             "dadi ji", "daada", "daadaji", "daada ji", "daadi", "daadiji", "daadi ji"]
